services:
  # Database service with pgvector extension
  db:
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    # No ports exposed to host - only accessible within the Docker network

  # Next.js application service
  nextapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/rag
      ANTHROPIC_API_KEY: your-anthropic-api-key
      OPENAI_API_KEY: your-openai-api-key
      EMBEDDING_MODEL: nomic-embed-text # choose ollama embedding model (we don't have the possibility to use remote models yet here)
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: